package employeemanagement.servlet;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

// @WebServlet maps this class to a URL path. When Tomcat receives
// a request for /hello, it routes it to this servlet instead of
// looking for a static file.
@WebServlet("/hello")
public class HelloServlet extends HttpServlet {

    // doGet() runs whenever this servlet receives an HTTP GET request
    // (e.g., someone clicking a link, or typing the URL directly).
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // Tell the browser what kind of content we're sending back.
        response.setContentType("text/html");

        // getWriter() gives us a stream to write the HTTP response body.
        PrintWriter out = response.getWriter();
        out.println("<!DOCTYPE html>");
        out.println("<html><head><title>Servlet Test</title></head><body>");
        out.println("<h1>Servlet is working!</h1>");
        out.println("<p>This response was generated by Java code, not a static file.</p>");
        out.println("<a href='index.html'>Back</a>");
        out.println("</body></html>");
    }
}